version: '3'
services:
   backend:
      build:
         context: .
         dockerfile: Dockerfile.dev
      container_name: backend-pikobar-development
      ports: 
         - 3333:3333
      env_file: 
        - .env
      networks:
        - gateway 
      restart: always

networks:
   gateway:
       external:
           name: jds-dev-network
